spring:
    jpa:
        hibernate:
            #ddl-auto: validate
            ddl-auto: create-drop
            database-platform: org.hibernate.dialect.H2Dialect
    datasource:
        url: jdbc:h2:~/tmp/testdb;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driverClassName: org.h2.Driver

flyway:
    enabled: true

management:
    port: 8081

server:
    port: 9000
